Added Issue Templates. Fixes #2
FahimFBA/assist-me pull request #8
Opened 2023-10-09 19:03 UTC by VividhPandey003

Fixes Add Issue Templates #2

2023-10-09 19:08 UTC, FahimFBA requested changes

2023-10-09 19:08 UTC, FahimFBA commented on .github/ISSUE_TEMPLATE/bug_report.md
> +title: ''
```suggestion
title: '[BUG] Give a suitable title'
```

2023-10-09 19:08 UTC, FahimFBA commented on .github/ISSUE_TEMPLATE/bug_report.md
> +labels: ''
```suggestion
labels: 'bug'
```

2023-10-09 19:08 UTC, FahimFBA commented on .github/ISSUE_TEMPLATE/feature_request.md
> +
```suggestion
title: '[FEAT.] Give a suitable title'
labels: 'enhancement'
assignees: ''
```

2023-10-09 19:08 UTC, FahimFBA commented on .github/ISSUE_TEMPLATE/others.md
> +
```suggestion
title: "[Other] Give it a suitable title"
labels: ''
assignees: ''
```

2023-10-09 19:11 UTC, FahimFBA commented
Please make the necessary changes.

2023-10-09 19:20 UTC, VividhPandey003 commented
> Please make the necessary changes.

Commited the suggested changes.

2023-10-10 03:31 UTC, FahimFBA approved these changes

2023-10-10 03:31 UTC, FahimFBA commented
Thank you for your contribution. 😃

2023-10-10 03:31 UTC, merged